df_site/df_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
import product.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', product.views.home, name = 'home'),
    path('product/',include('product.urls')),
    path('category/',include('category.urls')),
]

df_site/product/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns = [
        path('search/', views.search, name='search'),
        path('select/<category_name>', views.select_category, name ='select'),
        path('search_name/<search_key>', views.search_name, name='search_name'),         # search inside a product/ brand/ category page
        path('sort/<search_key>/<sort_type>', views.sort, name='sort'),         # search inside a product/ brand/ category page
        path('filter/<search_key>/<filter_type>', views.filter, name='filter'),         # search inside a product/ brand/ category page
]

df_site/df_site/templates/base.html
<!DOCTYPE html>
<html lang="en">

    {% load static %}

<head>
    <meta charset="utf-8">
    <title>DealFinder - Get The Best Deals</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>



<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'home' %}" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">D</span>DealFinder</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="{% url 'product:search' %}" method = "POST">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" name = "search_key" id = "search_key" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <button class = "btn btn-sm" type="submit"> <i class="fa fa-search" type = "submit"></i></button> 
                               
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                    <!-- <a href="" class="nav-item nav-link">Login</a> -->
                    <i class="fas fa-user-alt"></i>
            </div>
        </div>
    

        <div class="row align-items-center py-3 px-xl-5">
           
            {% for category in categories %}
                {% if forloop.counter <= 5 %}
            <div class="col-lg-2 col-4 text-left">
                            <a href="{% url 'product:select' category %}" class="nav-item nav-link">{{category}}</a>
             </div>
                {% endif %}
            {% endfor %}
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">More</a>
                <div class="dropdown-menu rounded-0 m-0">
                    {% for category in categories %}
                        {% if forloop.counter > 5 %}
                        <a href="{% url 'product:select' category %}" class="dropdown-item">{{category}}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
  <!-- need to show a more button for the other entries and that will reveal a list to scroll -->
            
 
        
        
    <!-- </div> -->
    <!-- Topbar End -->

    {% block body %}

    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
       
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">DealFinder</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                    Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

<style>
    .modal-xl {
    max-width: 80% !important;
}
</style>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js'%}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js'%}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js'%}"></script>
    <script src="{% static 'mail/contact.js'%}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js'%}"></script>

    



</body>

</html>